// <auto-generated />
using CaseStudy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseStudy.API.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250707221437_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseStudy.API.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("popularityScore")
                        .HasColumnType("float");

                    b.Property<string>("roseimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.Property<string>("whiteimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yellowimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Engagement Ring 1",
                            popularityScore = 0.84999999999999998,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG085-100P-R.jpg?v=1696588406",
                            weight = 2.1000000000000001,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG085-100P-W.jpg?v=1696588402",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG085-100P-Y.jpg?v=1696588368"
                        },
                        new
                        {
                            Id = 2,
                            name = "Engagement Ring 2",
                            popularityScore = 0.51000000000000001,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG012-R.jpg?v=1707727068",
                            weight = 3.3999999999999999,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG012-W.jpg?v=1707727068",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG012-Y.jpg?v=1707727068"
                        },
                        new
                        {
                            Id = 3,
                            name = "Engagement Ring 3",
                            popularityScore = 0.92000000000000004,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG020-100P-R.jpg?v=1683534032",
                            weight = 3.7999999999999998,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG020-100P-W.jpg?v=1683534032",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG020-100P-Y.jpg?v=1683534032"
                        },
                        new
                        {
                            Id = 4,
                            name = "Engagement Ring 4",
                            popularityScore = 0.88,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG022-100P-R.jpg?v=1683532153",
                            weight = 4.5,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG022-100P-W.jpg?v=1683532153",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG022-100P-Y.jpg?v=1683532153"
                        },
                        new
                        {
                            Id = 5,
                            name = "Engagement Ring 5",
                            popularityScore = 0.80000000000000004,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG074-100P-R.jpg?v=1696927124",
                            weight = 2.5,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG074-100P-W.jpg?v=1696927124",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG074-100P-Y.jpg?v=1696232035"
                        },
                        new
                        {
                            Id = 6,
                            name = "Engagement Ring 6",
                            popularityScore = 0.81999999999999995,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG075-100P-R.jpg?v=1696591802",
                            weight = 1.8,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG075-100P-W.jpg?v=1696591798",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG075-100P-Y.jpg?v=1696591786"
                        },
                        new
                        {
                            Id = 7,
                            name = "Engagement Ring 7",
                            popularityScore = 0.69999999999999996,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG094-100P-R.jpg?v=1696589214",
                            weight = 5.2000000000000002,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG094-100P-W.jpg?v=1696589210",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG094-100P-Y.jpg?v=1696589183"
                        },
                        new
                        {
                            Id = 8,
                            name = "Engagement Ring 8",
                            popularityScore = 0.90000000000000002,
                            roseimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG115-100P-R.jpg?v=1696596151",
                            weight = 3.7000000000000002,
                            whiteimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG115-100P-W.jpg?v=1696596147",
                            yellowimage = "https://cdn.shopify.com/s/files/1/0484/1429/4167/files/EG115-100P-Y.jpg?v=1696596076"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
